name: 'crowdin-action'

description: 'This action allows you to manage and synchronize localization resources with your Crowdin project'

branding:
  icon: 'refresh-cw'
  color: 'green'

inputs:
  # upload options
  upload_sources:
    description: 'Upload sources to Crowdin'
    default: 'true'
    required: false
  upload_translations:
    description: 'Upload translations to Crowdin'
    default: 'false'
    required: false
  auto_approve_imported:
    description: 'Automatically approves uploaded translations'
    default: 'false'
    required: false
  import_eq_suggestions:
    description: 'Defines whether to add translation if it is equal to source string in Crowdin project'
    default: 'false'
    required: false
  import_duplicates:
    description: 'Defines whether to add translation if there is the same translation already existing in Crowdin project'
    default: 'false'
    required: false

  # download options
  download_translations:
    description: 'Make pull request of Crowdin translations'
    default: 'false'
    required: false
  language:
    description: 'Use this option to download translations for a single specified language'
    required: false
  push_translations:
    description: 'Download translations with pushing to branch'
    default: 'true'
    required: false
  localization_branch_name:
    description: 'To download translations to the specified version branch'
    default: 'l10n_crowdin_action'
    required: false
  create_pull_request:
    description: 'Create pull request after pushing to branch'
    default: 'true'
    required: false

  # global options
  crowdin_branch_name:
    description: 'Option to upload or download files to the specified version branch in your Crowdin project'
    required: false
  identity:
    description: 'Option to specify a path to user-specific credentials'
    required: false
  config:
    description: 'Option to specify a path to the configuration file'
    required: false
  dryrun_action:
    description: 'Option to preview the list of managed files'
    default: 'false'
    required: false

  # config options
  project_id:
    description: 'Numerical ID of the project'
    required: false
  token:
    description: 'Personal access token required for authentication'
    required: false
  base_url:
    description: 'Base URL of Crowdin server for API requests execution'
    required: false
  base_path:
    description: 'Path to your project directory on a local machine'
    required: false
  source:
    description: 'Path to the source files'
    required: false
  translation:
    description: 'Path to the translation files'
    required: false

runs:
  using: docker
  image: 'Dockerfile'
