name: 'crowdin-action'

description: 'This action allows you to manage and synchronize localization resources with your Crowdin project'

branding:
  icon: 'refresh-cw'
  color: 'green'

inputs:
  # upload sources options
  upload_sources:
    description: 'Upload sources to Crowdin'
    default: 'true'
    required: false
  upload_sources_args:
    description: 'Additional arguments which will be passed to the `upload sources` cli command'
    default: ''
    required: false

  # upload translations options
  upload_translations:
    description: 'Upload translations to Crowdin'
    default: 'false'
    required: false
  upload_language:
    description: 'Use this option to upload translations for a single specified language - Case-Sensitive'
    required: false
  auto_approve_imported:
    description: 'Automatically approves uploaded translations'
    default: 'false'
    required: false
  import_eq_suggestions:
    description: 'Defines whether to add translation if it is equal to source string in Crowdin project'
    default: 'false'
    required: false
  upload_translations_args:
    description: 'Additional arguments which will be passed to the `upload translations` cli command'
    default: ''
    required: false

  # download sources options
  download_sources:
    description: 'Defines whether to download source files from the Crowdin project'
    default: 'false'
    required: false
  push_sources:
    description: 'Push downloaded sources to the branch'
    default: 'true'
    required: false
  download_sources_args:
    description: 'Additional arguments which will be passed to the `download sources` cli command'
    default: ''
    required: false

  # download translations options
  download_translations:
    description: 'Defines whether to download translation files from the Crowdin project'
    default: 'false'
    required: false
  download_language:
    description: 'Use this option to download translations for a single specified language'
    required: false
  download_bundle:
    description: 'Download bundle from Crowdin project (by ID)'
    default: ''
    required: false
  skip_untranslated_strings:
    description: 'Skip untranslated strings in exported files (does not work with .docx, .html, .md and other document files)'
    default: 'false'
    required: false
  skip_untranslated_files:
    description: 'Omit downloading not fully translated files'
    default: 'false'
    required: false
  export_only_approved:
    description: 'Include approved translations only in exported files. If not combined with --skip-untranslated-strings option, strings without approval are fulfilled with the source language'
    default: 'false'
    required: false
  push_translations:
    description: 'Push downloaded translations to the branch'
    default: 'true'
    required: false
  commit_message:
    description: 'Commit message for download translations'
    default: 'New Crowdin translations by GitHub Action'
    required: false
  localization_branch_name:
    description: 'To download translations to the specified version branch'
    default: 'l10n_crowdin_action'
    required: false
  create_pull_request:
    description: 'Create pull request after pushing to branch'
    default: 'true'
    required: false
  pull_request_title:
    description: 'The title of the new pull request'
    default: 'New Crowdin translations by GitHub Action'
    required: false
  pull_request_body:
    description: 'The contents of the pull request'
    required: false
  pull_request_assignees:
    description: 'Add up to 10 assignees to the created pull request (separated by comma)'
    required: false
  pull_request_reviewers:
    description: 'Usernames of people from whom a review is requested for this pull request (separated by comma)'
    required: false
  pull_request_team_reviewers:
    description: 'Team slugs from which a review is requested for this pull request (separated by comma)'
    required: false
  pull_request_labels:
    description: 'To add labels for created pull request'
    required: false
  pull_request_base_branch_name:
    description: 'Create pull request to specified branch instead of default one'
    required: false
  download_translations_args:
    description: 'Additional arguments which will be passed to the `download translations` cli command'
    default: ''
    required: false
  skip_ref_checkout:
    description: 'Skip default git checkout on GITHUB_REF'
    default: 'false'
    required: false

  # global options
  crowdin_branch_name:
    description: 'Option to upload or download files to the specified version branch in your Crowdin project'
    required: false
  config:
    description: 'Option to specify a path to the configuration file, without / at the beginning'
    required: false
  dryrun_action:
    description: 'Option to preview the list of managed files'
    default: 'false'
    required: false

  # GitHub (Enterprise) configuration
  github_base_url:
    description: 'Option to configure the base URL of GitHub server, if using GHE.'
    default: 'github.com'
    required: false
  github_api_base_url:
    description: 'Options to configure the base URL of GitHub server for API requests, if using GHE and different from api.github_base_url.'
    required: false
  github_user_name:
    description: 'Option to configure GitHub user name on commits.'
    default: 'Crowdin Bot'
    required: false
  github_user_email:
    description: 'Option to configure GitHub user email on commits.'
    default: 'support+bot@crowdin.com'
    required: false
  gpg_private_key:
    description: 'GPG private key in ASCII-armored format'
    required: false
  gpg_passphrase:
    description: 'GPG Passphrase'
    default: ''
    required: false

  # config options
  project_id:
    description: 'Numerical ID of the project'
    required: false
  token:
    description: 'Personal access token required for authentication'
    required: false
  base_url:
    description: 'Base URL of Crowdin server for API requests execution'
    required: false
  base_path:
    description: 'Path to your project directory on a local machine, without / at the beginning'
    required: false
  source:
    description: 'Path to the source files, without / at the beginning'
    required: false
  translation:
    description: 'Path to the translation files'
    required: false

  # command options
  command:
    description: 'Crowdin CLI command to execute'
    required: false
  command_args:
    description: 'Additional arguments which will be passed to the Crowdin CLI command'
    required: false
outputs:
  pull_request_url:
    description: 'The URL of the pull request created by the workflow'
  pull_request_number:
    description: 'The number of the pull request created by the workflow'

runs:
  using: docker
  image: 'Dockerfile'
